# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MiConnectProtocol.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17MiConnectProtocol.proto\x12\x05proto\"\xbf\x02\n\x07Payload\x12\x14\n\x0cversionMajor\x18\x01 \x01(\x05\x12\x14\n\x0cversionMinor\x18\x02 \x01(\x05\x12\x0c\n\x04\x61pps\x18\x03 \x01(\x0c\x12\r\n\x05\x66lags\x18\x04 \x01(\x0c\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0e\n\x06idHash\x18\x06 \x01(\x0c\x12\x12\n\ndeviceType\x18\x07 \x01(\x05\x12\x14\n\x0csecurityMode\x18\x08 \x01(\x05\x12\x10\n\x08\x61ppsData\x18\t \x03(\x0c\x12\x16\n\x0esupportSetting\x18\n \x03(\x0c\x12\x16\n\x0e\x63urrentSetting\x18\x0b \x03(\x0c\x12\x0f\n\x07wifiMac\x18\x0c \x01(\t\x12\x0e\n\x06\x61ppIds\x18\r \x03(\x05\x12\x10\n\x08\x63ommData\x18\x0e \x01(\x05\x12\r\n\x05ziped\x18\x0f \x01(\x08\x12\x10\n\x08wiredMac\x18\x10 \x01(\t\x12\r\n\x05\x62tMac\x18\x11 \x01(\t\"=\n\tContainer\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.proto.Payload\x12\x12\n\nsequenceId\x18\x0e \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MiConnectProtocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYLOAD']._serialized_start=35
  _globals['_PAYLOAD']._serialized_end=354
  _globals['_CONTAINER']._serialized_start=356
  _globals['_CONTAINER']._serialized_end=417
# @@protoc_insertion_point(module_scope)
