name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install pytest hatch versioningit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build protobuf
        run: |
          python ./build_protobuf.py
      - name: Build dist
        run: |
          hatch build
      - name: Test with pytest
        run: |
          pytest ./tests/
      - name: Upload release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
